### PR TITLE
Defibrillation now works on deceased.

### PR DESCRIPTION
**Pull request by nevimer**
It's 2565 - Death shouldn't be final. This patch allows the defibrilation to revive deceased patients, provided medical tends to their other issues death brings.

What it does:
- Removes brain's necrotic status, changes to bleeding.
- If you are dead, removes 1 brain damage from you ONLY if you are dead (200 brain damage)
- Prompts you to reenter your body if you wish to have a chance
- Starts your heart aswell (if you have one) as removes all your dead status flags(ghost, etc).

What it does not
- Replace actually fixing someone
- Unrot other organs
- aheal
- keep them alive
- replace cloning, just another tool to keep someone in a round (for roleplay reasons, you could add to med record clone or revive)

How to revive someone with defib:
- Fix their body as best as you can, give them stabilizing reagents.
- Defib them
- If you did enough, they should be on the cusp of death again
- if you didn't do enough, they will die immediately again.  

Why this is good:
Gives an option for keeping someone in the round other than cloning (which comes off by default) and provides revival means for races that cannot be cloned. Sometimes this will be faster than cloning, sometimes it will be slower. Players can put IC preferences in medical records (DNC, DNR, Clone only, Revive only)

Keeping people in the game is good for population and newbie friendly vs "hardcore mode" type things. 

We should be focusing on outcomes over gameplay purity

:cl:
tweak: Defib's now revive the deceased.
/:cl:

### CODE REVIEW

**Comment by Soulstolen** [comment]
I know laces exist, but this still brings me on the topic of the reason as to why RR (which again, doesn't exist cause laces, unless you remove it from the person) is good for the flow of Baycode antags. 
Brainmed is punishing, and a single breath of no air in a vacuum can fuck your lungs, a single shot to the chest can bring you to crit. These dangers, and the idea of death and possibly not being able to revived, give value to encouraging roleplay, hostage situations where security doesn't unga in knowing the person will live no matter what they fuck up. 

The main argument is "But laces don't give medical anything to do." Firstly, admins can help with making medical work when needed better, and well more than 90% of the time, dying takes so long that they get saved as long as they can be found. Sure, we give medical something more to do, but we take away from a huge part of what makes Brainmed work perfectly with HRP antags. Personally, I vouch for the removal of laces, and an increase in how long it takes for brain death to occur, but that is a battle for another time. I believe we should stick with the status quo, keep death meaningful and sacred, make funerals actually matter, rather than. "Wow the person gave up and isn't going back in their body, kinda gay" And have more of, "He's.. Dead, there's nothing we can do to save them, I'm so sorry." Rounds are not canon either, and this gives people the ability to Ironman mode much better, we on hestia had many people who once their character died, a vast funeral was held, everyone mourned, and a great solider was lost, but always remembered. Making this change takes away the genuine idea of a death that can't be revereted.

Ponder on how this improves roleplay, and how many alternatives there is already to get around this: laces and even having the ability to just, play another character, if you have multiple.

**Comment by Codingale** [comment]
I propose an implementation change, where you can revive them like this if it's been less than five minutes. I think that's a better compromise.

Having it happen after 3 hours is over the top, whereas 5 minutes to me makes sense, if you just died from something preventable etc., without getting rid of Round Removal abilities; so antags can still kill them and remove them from the round if they hide the body or just sit there to confirm the kill which I think would allow some post-kill RP possibly… I've seen a pretty good role play following murders before, and having a slight mechanical encouragement would be good too.

**Comment by miniusAreas** [comment]
I'd like to agree with the above. RR is important for the flow of bay, however defibulating a corpse that's sat for an hour doesn't fit right. Someone who's been dead for less than five minutes tops makes a ton of sense, and helps with medical a bit, as I've died on the table several times.

I also want to put out a secondary thing here, while I'm at it. I've come to realize that code does not influence how people RP - rather, it attracts people with expectations and meaning to RP at a level that that codebase is associated with. As others have said before this feels too much like TG - the two codebases are different have have their reasons for being that way. TG is built for faster-paced quick and sometimes chaotic rounds, whereas bay is built for longer rounds with more dangerous outcomes for things going wrong, as well as longer buildups to an end. Changing things like the risks of death or the dangers of things messes with these paces and expectations, and throws everything off massively.

**Comment by Guidesu** [comment]
Do what said above.
You can revive people for about five minutes.
Also makes defib bags plus sleeper cryo go around to 20 minutes.

**Comment by Guidesu** [comment]
Then you good to go mate.

**Comment by HawkerTheGreat** [comment]
Upon thinking about this merge for a while, I wanted to share some possible problems with the idea of using the defib past time of death. 

When someone dies of braindeath, their organs will eventually reach the necrotic state. This will require all of their organs to be printed, wasting a bunch of valuable resources that could instead be used for re-lacing people. Since surgery is heavily based on skill, without master rank surgery, someone could spend an upwards of ten to twenty minutes just replacing all of the issues in a necrotic, bloodless body. As much as I hate to mention, there is also the idea of abusing the ability to revive people past braindeath. As you know, chemicals and organ states other than necrotic don't progress when someone is dead. Sometimes the difficulty of keeping someone alive is in preventing their state from getting worse. Thus making braindeath a more optimal way of fixing issues, by killing the person and reviving them without worrying about time limits. Essentially if you run out of time, you can revive them and let them die to reset the timer.

Resleeving DOES indeed take a long time and it serves to punish the player for disregarding their character's safety or getting caught in a bad position, but I feel It's a vital part of the HRP gameplay loop. And it frees up doctors to save other's since it generally does not need to be babysat with the exception of one surgery.

**Comment by Guidesu** [comment]
We will test this PR for a few days.

**Pull request merged**
